export const CarsMake = [
    { Name: "Honda", value: "honda" },
    { Name: "Suzuki", value: "suzuki" },
    { Name: "Toyota", value: "toyota" },
    { Name: "MG", value: "mg" },
    { Name: "Nissan", value: "nissan" },
    { Name: "Daihatsu", value: "daihatsu" },
    { Name: "Hyundai", value: "hyundai" },
    { Name: "Kia", value: "kia" },
    { Name: "Changan", value: "changan" },
    { Name: "FAW", value: "faw" },
    { Name: "Chevrolet", value: "chevrolet" },
    { Name: "Ford", value: "ford" },
    { Name: "Mercedes-Benz", value: "mercedes" },
    { Name: "BMW", value: "bmw" },
    { Name: "Audi", value: "audi" },
    { Name: "Jeep", value: "jeep" },
    { Name: "Lexus", value: "lexus" },
    { Name: "Subaru", value: "subaru" },
    { Name: "Mitsubishi", value: "mitsubishi" },
    { Name: "Peugeot", value: "peugeot" },
  ];
  